name: Backport
on:
  workflow_call:
    inputs:
      label-pattern:
        description: 'Label pattern for backport branches (e.g. "backport *")'
        type: string
        default: 'backport *'

jobs:
  backport:
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.merged == true &&
      contains(toJson(github.event.pull_request.labels), 'backport')
    steps:
      - name: Backport
        uses: korthout/backport-action@66065406958f46e82238fd59546f5a99e69e22aa # v4.5.2
        with:
          label_pattern: "${{ inputs.label-pattern }}"
          merge_method: "none"
